spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true
    username: root
    password:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0