spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true
    username: root
    password:
  application:
    name: product-service

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0